name: Salesforce Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - main  # Trigger on PR merge into 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Salesforce CLI (SFDX) using the correct action
      - name: Set up Salesforce CLI
        uses: forcedotcom/cli-action@v1.0.0
        with:
          sfdx-cli-version: latest
          
      # Authenticate to Salesforce Org using a GitHub secret
      - name: Authenticate to Salesforce Org
        run: echo ${{ secrets.SF_AUTH }} | sfdx auth:sfdxurl:store -f -

      # Deploy source to Salesforce Org
      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app --targetusername ${{ secrets.SF_ALIAS }} --checkonly --verbose
